language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; sudo apt-get update -qq; fi

install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi

script:
  make test

branches:
  only:
    - master

notifications:
  email: false

osx_image:
  xcode61
