language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6.3
    - g++-6.3
    - clang

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make test CXX="g++-6.3" CC="gcc-6.3"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make test; fi

branches:
  only:
    - master

notifications:
  email: false

osx_image: xcode9.3
